M48
; DRILL file {KiCad 6.99.0-unknown-455e330f3b~148~ubuntu20.04.1} date Sat Apr 23 09:38:19 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-23T09:38:19+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.99.0-unknown-455e330f3b~148~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X145.9Y-90.375
X145.9Y-97.375
T0
M30
